POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "NLW Expert",
    "details": "Evento de programação, cujo participante pode acompanhar e reproduzir em aulas a criação de um projeto de portfólio.",
    "maximumAttendees": null
}

###

POST http://localhost:3333/events/593770c5-05b7-459e-a7cf-971b074d670c/attendees
Content-Type: application/json

{
    "name": "Larissa Diniz",
    "email": "laridiniz@email.com"
    
}

###
GET http://localhost:3333/events/593770c5-05b7-459e-a7cf-971b074d670c

###
GET http://localhost:3333/events/593770c5-05b7-459e-a7cf-971b074d670c/attendees

###
GET http://localhost:3333/attendees/1/badge

###
GET http://localhost:3333/attendees/2/checkin

###

POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "NLW Summit",
    "details": "Para quem é apaixonado por programanão.",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Evento de Teste",
    "details": null,
    "maximumAttendees": 1
}
